services:
  db:
    container_name: db-prod
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: every_meeting_prod
    ports:
      - 3049:3306
    networks:
      - every-meeting-prod

  client:
    container_name: client-prod
    build:
      context: ./client
      dockerfile: ./Dockerfile.prod
    ports:
      - 3041:80
    pull_policy: build
    networks:
      - every-meeting-prod

  api:
    container_name: api-prod
    build:
      context: ./
      dockerfile: ./api/Dockerfile.prod
    depends_on:
      - db
    ports:
      - 3044:80
    pull_policy: build
    networks:
      - every-meeting-prod

  phpmyadmin:
    container_name: phpmyadmin-prod
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3046:80
    environment:
      PMA_HOST: db
    networks:
      - every-meeting-prod

  event-logger-service:
    build: ./event-logger
    container_name: event-logger-service-prod
    ports:
      - "3042:3042"
    pull_policy: build
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://event-logger-db:27017/eventlogger
    depends_on:
      - event-logger-db
    networks:
      - events-logger-network

  event-logger-db:
    image: mongo:latest
    container_name: event-logger-db-prod
    ports:
      - "3043:27017"
    volumes:
      - mongodb_data_prod:/data/db
    networks:
      - events-logger-network

networks:
  every-meeting-prod:
    driver: bridge
  events-logger-network:
    driver: bridge

volumes:
  - mongodb_data_prod

