services:
  api-dev:
    container_name: every-meeting-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    volumes:
      - ./api:/var/www/html
    environment:
      - XDEBUG_MODE=coverage
    depends_on:
      - db
    # networks:
      # - mynetwork

  client-dev:
    container_name: every-meeting-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    volumes:
      - ./client:/var/www/client
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - api-dev
    # networks:
      # - mynetwork

  db:
    image: mysql:latest 
    ports:
      - "3306:3306"   
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: everymeeting
    # networks:
      # - mynetwork
    volumes:
      - "my-volume:/var/lib/mysql"
    
  phpmyadmin-dev:
    image: phpmyadmin:latest
    ports:
      - "8080:80"  
    environment:
      - PMA_HOST=db
    # networks:
      # - mynetwork

  event-logger-service:
    build: ./event-logger
    container_name: event-logger-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://event-logger-db:27017/eventlogger
    depends_on:
      - event-logger-db
    networks:
      - events-logger-network

  event-logger-db:
    image: mongo:latest
    container_name: event-logger-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - events-logger-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

# networks:
  # mynetwork:

networks:
  events-logger-network:
    driver: bridge

volumes:
  my-volume:
  mongodb_data:
