# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#         allow_credentials: true
#     paths:
#         '^/': 
#             allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#             allow_headers: ['Content-Type', 'Authorization']
#             allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
#             allow_credentials: true
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
        allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
        allow_headers: ["Content-Type", "Authorization", "Access-Control-Allow-Origin"]
        expose_headers: ["Link"]
        allow_credentials: true
        max_age: 3600
    paths:
        "^/": null