security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false        
        login:
            pattern: ^/admin/
            provider: app_user_provider
            logout:
                path: /logout
        main: 
            pattern: ^/api/auth
            methods: [ POST ]
            json_login:
                check_path: /api/auth
                provider: app_user_provider
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure       
        refresh_jwt:
            refresh_jwt:
                check_path: /api/token/refresh
            logout:
                path: api_token_invalidate        
        api:
            pattern: ^/api/
            stateless: true
            entry_point: jwt
            provider: app_user_provider
            jwt: ~
    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
        - { path: ^/docs, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI docs
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/to_do_list_items, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/, roles: [ROLE_ADMIN,IS_AUTHENTICATED_FULLY] }
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 
                time_cost: 3 
                memory_cost: 10 
