controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_api_auth:
    path: /auth
    methods: [POST]
api_refresh_token:
    path: /token/refresh
