controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_api_auth:
    path: /api/auth
    methods: [POST]
#test
home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'base.html.twig'
