name: Pull Request Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_NAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for React client)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        uses: actions/setup-node@v2
        with:
          node-version: 'lts'

      - name: Install React dependencies
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        run: |
          cd client
          npm install

      - name: Run ESLint and Prettier (React client)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        run: |
          cd client
          npm run format
          npm run lint

      - name: Set up PHP (for Symfony API)
        if: startsWith(github.job, 'ubuntu')
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install API dependencies
        if: startsWith(github.job, 'ubuntu')
        run: |
          cd api
          composer install

      - name: Check Security (Symfony API)
        if: startsWith(github.job, 'ubuntu')
        run: |
          cd api
          symfony check:security

      - name: Code Sniffer (Symfony API)
        if: startsWith(github.job, 'ubuntu')
        run: |
          cd api
          php ./vendor/bin/phpcs
          php ./vendor/bin/phpcbf

      - name: Set up Node.js (for React client)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        uses: actions/setup-node@v2
        with:
          node-version: 'lts'

      - name: Set up PHP (for Symfony API) - Windows and macOS
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Set up QEMU
        if: matrix.os == 'windows-latest'
        uses: docker/setup-qemu-action@v2
  
      - name: Set up Docker Buildx
        if: matrix.os == 'windows-latest' || matrix.os == 'macos-latest'
        uses: docker/setup-buildx-action@v1
  
      - name: Build and Push Client Image
        env:
          DOCKER_BUILDKIT: 1
        run: |
            cd client
            docker build -t $DOCKERHUB_USERNAME/client-image:latest .
            docker push $DOCKERHUB_NAME/client-image:latest
  
      - name: Build and Push API Image
        env:
            DOCKER_BUILDKIT: 1
        run: |
            cd api
            docker build -t $DOCKERHUB_USERNAME/api-image:latest .
            docker push $DOCKERHUB_NAME/api-image:latest

              





