name: Pull Request Tests

on: [pull_request]

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for React client)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        uses: actions/setup-node@v2
        with:
          node-version: 'lts'

      - name: Install React dependencies
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        run: |
          cd client
          npm install

      - name: Run ESLint and Prettier (React client)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        run: |
          cd client
          npm run format
          npm run lint

      - name: Set up PHP (for Symfony API)
        if: startsWith(github.job, 'ubuntu')
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install API dependencies
        if: startsWith(github.job, 'ubuntu')
        run: |
          cd api
          composer install

      - name: Check Security (Symfony API)
        if: startsWith(github.job, 'ubuntu')
        run: |
          cd api
          symfony check:security

      - name: Code Sniffer (Symfony API)
        if: startsWith(github.job, 'ubuntu')
        run: |
          cd api
          php ./vendor/bin/phpcs
          php ./vendor/bin/phpcbf

      - name: Set up Node.js (for React client)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        uses: actions/setup-node@v2
        with:
          node-version: 'lts'

      - name: Set up PHP (for Symfony API) - Windows and macOS
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Login to Docker Hub
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push Client Docker Image (Windows and macOS)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        working-directory: ./client
        run: |
            docker build -t ${{ secrets.DOCKERHUB_NAME }}/everymeeting:latest -f Dockerfile .
            docker push ${{ secrets.DOCKERHUB_NAME }}/everymeeting:latest
  
      - name: Build and Push API Docker Image (Windows and macOS)
        if: startsWith(github.job, 'windows') || startsWith(github.job, 'macos')
        working-directory: ./api
        run: |
            docker build -t ${{ secrets.DOCKERHUB_NAME }}/everymeeting:latest -f Dockerfile .
            docker push ${{ secrets.DOCKERHUB_NAME }}/everymeeting:latest        





